### ISSUE TITLE
Parte 2 #ElMásPopular / Especificar condición de palabra "Leaderboard"

### ISSUE THREAD

**Issue by eduardoequis** [undefinedschool/project-4-node-jokes#1]
Hay varios detalles que se pueden especificar mejor con respecto a #ElMásPopular:

La condición dice que "Si el programa recibe **además** el string "leaderboard" como parte del input..." debe ocurrir algo más. ¿Qué pasa con el otro string ingresado?

¿El otro string ingresado debe seguir devolviendo un chiste desde la API? Es decir en consola se mostraría "chiste" + "ElMasPopular". ¿O todo ese proceso se cancela y sólo mostramos el leaderboard?

Otro detalle que se puede especificar mejor: ¿Qué pasa si sólo ingresamos la palabra leaderboard en el input? ¿se debe mostrar #ElMásPopular o debe buscarse un chiste con la palabra "leaderboard"? 

Para dejar más claro esto estaría bueno definir si leaderboard activa una función cuando:

1. Es ingresada en el input después de otra palabra.

2. Si está acompañada de otra palabra indistintamente de su posición

3. Si es una "palabra reservada" sólo para llamar a #ElMásPopular. Que si se ingresa antes o después de otra palabra, siempre llama a la función.

**Comment by nhsz** [comment]
La idea era que siga buscando chistes pero **loguee por consola sólo el más popular** (incluyendo el resultado de la última búsqueda para calcular esto).

Para evitar confusiones y simplificar, voy a cambiar la definición de la parte 2: la condición para que se busque y retorne el más popular es que el usuario ingrese `leaderboard` como keyword de búsqueda, sin ninguna otra palabra extra, como en la 1ra parte.
